[package]
name = "count_dominant_set"
version = "0.1.0"
authors = ["Victor Deleau <victor.deleau@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
